### ISSUE TITLE
Whos Prop is it

### ISSUE THREAD

**Issue by deinemudda32** [FPtje/Falcos-Prop-protection#118]
You can only see whos prop it is with physgun.
Could there be an option to see it even as normal person with every weapon.

**Comment by 00875** [comment]
I think we need only see it with Physgun and Tool. Why weapons?...

**Comment by deinemudda32** [comment]
I own a sandbox fight server.
Mainly you dont have a physgun.
And sandbox is home of mingebaging, so It would be good to see.

**Comment by TheEMP** [comment]
Thank god I asked about this months ago but Falco said it was done intentionally http://forum.darkrp.com/threads/is-this-something-that-was-done-intentionally.2969/

**Comment by FPtje** [comment]
Holy shit I totally misunderstood your post there! I obviously didn't get that you meant the issue that this commit solves. Instead I thought you asked me to make it so you always see the PhysgunPickup touch reason, regardless of what weapon you're holding. That's why I said that it should say "no" when you're holding the toolgun. 

But you described that it didn't say "no" when holding the toolgun, it didn't say anything at all!

Bad reading, definitely bad reading. Sorry.
