### ISSUE TITLE
ServerGuard ignoring FPP private setting 'I want to pick up players'

### ISSUE THREAD

**Issue by fruitwasp** [FPtje/Falcos-Prop-protection#131]
ServerGuard seems to ignore the FPP private setting 'I want to pick up players'.

Something wrong on FPP's end or should I contact the ServerGuard developers?

**Comment by FPtje** [comment]
Nah, that's an FPP <-> FAdmin thing. FAdmin listens to it, but the reason it exists in FPP is because of the unchecking of it, not the checking of it.

When unchecked, FPP will try to prevent admins from picking up players. When checked, FPP does nothing. The important bit here is "try to", because if severguard hooks run before FPP, it will not be stopped.

The option is a bit confusing, I admit.
