### ISSUE TITLE
Suggestion, Ability to add fallback user.

### ISSUE THREAD

**Issue by LuaTenshi** [FPtje/Falcos-Prop-protection#189]
It would be nice to have a user to fallback to if you happen to crash or disconnect. Or just want to leave, but don't want your stuff to vanish. (For example a base you are sharing with a friend who is going to continue playing.)

The idea is that you specify him as a fallback and once you leave or crash or whatever everything you own, will now belong to them. I think this feature would not only be very unique but also really useful.

**Comment by FPtje** [comment]
It has to be set once per session, I don't think it would be useful to save it. I've tried to account for different scenarios, but it's hard to test everything. Things like chaining fallback users (A disconnects and has B as fallback, who disconnects after with C as fallback. A's props then belong to C until A rejoins)

I haven't pushed this to DarkRP or the workshop. I want you to thoroughly test it first in a live server. I've been able to run some tests in multirun, but since the two mes had the same SteamID, my testing setup might be crucially different than a real world environment. Same with bots.
