### ISSUE TITLE
FPP needs a lot of resources

### ISSUE THREAD

**Issue by mcNuggets1** [FPtje/Falcos-Prop-protection#208]
FPP is so far, besides FAdmin and DarkRP the most expensive addon listed in FProfiler for example.

All 3 addons include useless loops which could be reworked for more performance.
Some of them aren't needed and to use a hook would be way easier.

Servers with a huge entity count are therefore fucked.

I optimized nearly all of my addons for huge entitycounts, but I don't feel the way after optimizing fadmin or fpp.

I don't have time to fix this all up myself and send a pull request, most likely because my coding style is different. (I use tabs and a compact coding style)

**Comment by FPtje** [comment]
Fpp does things in bulk. The bulks are big, but performance is fine
otherwise.

**Comment by mcNuggets1** [comment]
FProfiler tells me in 8 different cases it is the most performance fuckery addon on my servers.
Even on sandbox.

**Comment by mcNuggets1** [comment]
For example if we just want to get a bunch of entities owned by a player, don't run ents.GetAll().
Just add entities by a specified player in a table and then loop the table.
That is then 100 entries, instead of 5000.

**Comment by FPtje** [comment]
FProfiler is quite a bit more nuanced than that. For one it doesn't point at entire addons, it points at individual functions and their call stacks. You mention 8 different instances, but for all I know they might all be part of the same call stack.

That and my previous statement still holds. FPP is expensive on events, but specifically optimised to be cheap in between events, which is most of the time.

**Comment by mcNuggets1** [comment]
Every function with a ents* loop is mentioned in FProfiler.
There is alot to optimize. Too much, so I should just close this.

**Comment by FPtje** [comment]
Look, I've known FPP has had performance issues from the moment I made FProfiler. I've just been hoping no one would find out because it would require quite a bit of work. Also, I had somewhat recently put a lot of effort in optimising it. Right now everything is calculated when things change. Think of someone joining, someone becoming admin, the fpp settings being changed. Such events potentially have an effect on all entities for all players. Never mind the ents.GetAll loops in which lists of ents being generated, the problem lies a level of abstraction higher: the complexity of the entire algorithm being "for every ent for every player " in the worst case. Your proposed optimisation likely won't have much of an impact on that.

This method *does* have one **huge** benefit: the function that returns whether player such can physgun prop so and why (not) just returns the values of some pre-calculated variables. That's super useful because those functions are called very, *very* often. Back in the day, when FPP naively calculated touch info when requested, the server took a major performance hit. People seriously complained about general slowness with FPP installed. The optimisation moved the constant performance hit to simple, but big spikes on events, recalculating touch data for entities that might be affected by the event. Of course being clever enough not to look at entities that can't possibly be affected. 

That still leaves you with spikes on join, rank change or the full recalculation when you change a setting. The solution for that has been in my mind for ages too: lazy evaluation. Calculate touch data on request, cache results and clear appropriate caches on events. That should solve the performance issue much more efficiently than looking at some specific ents.GetAll loops ever will. 

I just haven't had the motivation yet to implement this change.

**Comment by roboderpy** [comment]
@mcNuggets1 did you mean something like this list:
https://github.com/roboderpy/dpp/blob/master/lua/dpp/sv_functions.lua#L292
https://github.com/roboderpy/dpp/blob/master/lua/dpp/sv_init.lua#L149
Instead of `ents.GetAll()`?

**Comment by FPtje** [comment]
How would that be more effective than the measure I described in my previous post?

**Comment by FPtje** [comment]
I've done a bunch of optimisations. Some are pretty big. When a player joined, for instance, the touch data for that player was calculated at least three times. I brought that back to one. I've also applied some micro optimisations to the most called function. See the commits for details.

I'll let you test this for a week or so before I put this version on the workshop and merge it with DarkRP. Please report any problems.

Note: To test with DarkRP, please disable the built-in fpp in the `disabled_defaults.lua` of the DarkRPMod.

**Comment by mcNuggets1** [comment]
Thank you, I will report back bugs if I find some.

**Comment by mcNuggets1** [comment]
No problems so far.

**Comment by FPtje** [comment]
Merged with DarkRP and shipped on the shop of work yes.
