### ISSUE TITLE
Mysql issue

### ISSUE THREAD

**Issue by deadspidervenom** [FPtje/Falcos-Prop-protection#268]
So whenever i enable mysql it stops saving settings.

The owner says that its not writing to the database either.

**Comment by FPtje** [comment]
Not a help forum

**Comment by FPtje** [comment]
Go to forum.darkrp.com

**Comment by deadspidervenom** [comment]
Umm i was not asking for help with darkrp i was reporting a issue with falcos prop protection. Nice assumptions.

**Comment by FPtje** [comment]
Still, the DarkRP forum is for FPP as well. The issues page on this repository is only for bugs in my code and feature requests. Settings not saving in the MySQL database happens to a ton of people who have either misconfigured it, use out of date versions or have conflicting addons.

If you're filing a bug report, you need to make a case that it's FPP's fault that it's not working, not one of the above mentioned causes. Otherwise the only thing I can reasonably reply is "works for me".

**Comment by deadspidervenom** [comment]
i apologize that my report has all the information i had, that it was working with sqlite and that it stopped working the moment we turned it to mysql, the other issue that you directed me to the darkrp forum, turned out to be a conflict between two addons that did not make sense but it took me 3 days to figure that out, because everyone either refused to help, or directed me else where.

However sense you made it clear that you dont want to spend the time and dont have the patience to write "Please visit the forum its probably just a --insert basic non-bug issue here--." to at least direct people more then having them repeat the damn issue too everyone under the sun for 3 days, until one of them suggests it might be a conflict with x addon. However its fine now, i solved the problem. Just wont use FPP.

**Comment by FPtje** [comment]
I hate to see you go, but the question is what would you expect from me as author/maintainer of FPP? Several times in the past I have asked to debug problems on people's server. I would join the server, run some diagnostic Lua (requires superadmin/rcon privilege). In the end it turned out to be mostly user error.

With MySQL not saving things I would specifically expect there to be errors. I've encountered several cases where people said there were no errors, but when I spent hours to arrange a look at the server's console I found myself saying "What's this then?". In this case a very simple connection error can explain all the problems in this issue. For all I know you don't even know where to look for errors.

Either way I would be required to spend hours every time someone asks this kind of support, where all the information I have is "it doesn't save". It's the difference between asking for support and reporting a bug. I feel responsible for solving bugs in FPP, but I cannot be demanded to spend hours per person giving individual support. This entire project is done in my free time, you cannot demand me to spend my free time on you.

On another note, I'm all in favor of shoving big red errors in people's faces when something goes wrong. Whether it's a conflicting addon or bad configuration, an error showing superadmins what's wrong and how it can be solved can help prevent frustrations like the one you're having. If you ever do find the cause, *tell* me about it. I can write code that prevents frustrations with other people.
