### ISSUE TITLE
Anti E2 Mingery is lagging complex E2's

### ISSUE THREAD

**Issue by Bryantdl7** [FPtje/Falcos-Prop-protection#295]
Please look at the two photos for example: 

With anti mingery turned off 
![image](https://user-images.githubusercontent.com/5564661/126915801-ad84e02d-a419-4156-830f-6b78909bf063.png)

the second I disable anti e2 mingery:
![image](https://user-images.githubusercontent.com/5564661/126915954-274987c0-d2c0-4ea7-932e-64714431bbed.png)

As you can see, there is a significant different in CPUtimes the second this is modified. I am not sure if something changes with your checks recently to make this take up more processing power in how you prevent mingery, but it affects build servers significantly. 

Thanks in advance!

**Comment by FPtje** [comment]
The only thing that changed recently is an `IsValid` check in #293. I'm not at all convinced that this could cause an extreme performance degradation though. Validity  checks are very cheap with regards to performance. 

Either way, it is expected that there is some performance difference between having the option on or off. Specifically when you use the `applyForce(e:v)` function in your e2. This is because it has to do something to do its work.

You could check before and after #293, but I honestly doubt that you will see a statistically significant difference. If there's a bottleneck, I expect it to be in getting the constrained entities or setting the collision group. That is something it has done since the beginning.

**Comment by FPtje** [comment]
Closing. If you have updates you can still post in this issue.
