### ISSUE TITLE
Issue: the hud info sometimes finds the wrong owner of props

### ISSUE THREAD

**Issue by wrefgtzweve** [FPtje/Falcos-Prop-protection#298]
I finally managed to find a repeatable instance of this happening. The wire door tool from wire extras has a door which is owned by the world with a player owned chip underneath it. Looking at this world owned entity frequently shows a different owner than it actually is, for example my friend messing around with his props was far away yet it still showed his ownership
![image](https://user-images.githubusercontent.com/69946827/129767620-ecf1224c-0315-4aff-baa2-5609a03fd6ac.png)
![image](https://user-images.githubusercontent.com/69946827/129767634-32799d02-1ac7-4938-87ee-a3dae47894ea.png)
![image](https://user-images.githubusercontent.com/69946827/129767657-4c6e0fea-0507-4096-b137-f464ba75ffe2.png)

**Comment by wrefgtzweve** [comment]
Sometimes shows the complete wrong owner, yet when i try to pick it up it actually allows me to
![image](https://user-images.githubusercontent.com/69946827/129767975-6a25c8e6-c233-47e3-9211-601e566c100a.png)
![image](https://user-images.githubusercontent.com/69946827/129768041-2592212c-82af-48b4-8b18-4265e85f4d95.png)

**Comment by FlorianLeChat** [comment]
I can also confirm this from some recent changes but I can't reproduce it on demand.

**Comment by FPtje** [comment]
Aha, this is actually a funny one. Nice find! With the wire door I could reproduce it. The code ran a ray check, and it just grabbed the first entity from it, assuming that `ents.FindInRay` returns entities in the order of passing the ray. This is not necessarily the case, the order, AFAIK, is arbitrary.

That means that you may see the owner of the prop you're looking at, but you may also see the prop behind it, or a prop behind that prop. Maybe a prop at the other side of the map!

Should be fixed in latest!
