### ISSUE TITLE
Configuration option to toggle big-prop exponential backoff

### ISSUE THREAD

**Issue by liondadev** [FPtje/Falcos-Prop-protection#319]
I'd love to switch to FPP for a less-restrictive system on my server, but one thing constantly annoys me.

When spawning any big prop, the anti-big-prop-spawning-thing kicks in. **This is good that spawning big props has a delay**, but the "backoff" (how the timer gets reset on every prop spawn) is incredibly annoying to everyone. You have no way of knowing when the timer is over, so you just have to wait and hope. A config option to disable this in the antispam settings will help. I'd be willing to attempt to cobble together a PR (might as well, this is my feature request) if none else has time.

Thanks for the awesome prop protection system, hope you consider this.

**Comment by FPtje** [comment]
That's an interesting idea. I'll have to dive into what the current logic is, but I'll see what I can do.

One idea that immediately came to mind, is to tie the notification time to the time you're not allowed to spawn the prop. That way, the notification disappearing off the screen means you can spawn your next prop.

**Comment by FPtje** [comment]
I just pushed an update that implements the notification time. With that, I also found that the whole implementation was kinda broken. The time it _said_ that you needed to wait, wasn't _actually_ the time you needed to wait. This is now also fixed in the latest version.

I think this might actually have been the source of your frustration. Could you try the latest version from GitHub and see if it's still as frustrating? Thanks

**Comment by liondadev** [comment]
Just tested and I can confirm it feels a lot less annoying to use, and definitely more intuitive.

Thanks for still actively maintaining this for so long :)
