### ISSUE TITLE
"Trying to send an overflowed net message" - FPP Lua Error

### ISSUE THREAD

**Issue by CryptAlchemy** [FPtje/Falcos-Prop-protection#323]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE DISCORD INSTEAD: https://darkrp.page.link/discord )

### Description of the bug
[//]: # (Describe the issue as accurately as possible)
The bug occurs right before a player is authed and is an overflow of the `net` library, see the following screenshot:
<img width="617" alt="image" src="https://github.com/FPtje/DarkRP/assets/7506395/e9c35c52-75e7-4b70-a4ee-37397ab29361">
This happens consistently when every player loads in.
It subsequently shows this:
<img width="285" alt="image" src="https://github.com/FPtje/DarkRP/assets/7506395/0c83683b-c5fe-4072-8765-17a9c8b4b469">

### How to make the bug happen
[//]: # (Knowing how to make a bug happen allows the developers to figure out)
[//]: # (what the cause of the problem is and whether a certain fix solves it)
The cause of the problem could be a lot of entities that DarkRP is trying to send to the client; there are a _lot_ of entities on this particular server.

### Lua errors
[//]: # (Note that errors on server startup are more important than other ones)
[//]: # (because they can cause other errors. Always look in the startup log of the server!)
Specified above.

### Why the developer of DarkRP is responsible for this issue
[//]: # (By posting on Github, you ask the developers of DarkRP to solve the problem)
[//]: # (It may seem obvious to you, but you have to make clear why they are the right people to look at it)
The developer is responsible for this issue as it's not related to any addon, particular Garry's Mod configuration, etc; it's solely related to the DarkRP addon.

**Comment by FPtje** [comment]
Thanks, by the way for the clear information on the bug. Because of that I know precisely what the problem is and what can be done about it.

I sadly don't have the means to look at this the coming days, but I will try to look at it as soon as I can.

**Comment by CryptAlchemy** [comment]
> The only thing I wonder is hoe it could take so many years before this was reported. Was the entity limit raised recently by chance?

That is a good question, yeah. Looks like the entity limit is ["16384 entities, split into two groups of 8192."](https://developer.valvesoftware.com/wiki/Entity_limit#:~:text=16384%20entities%2C%20split%20into%20two%20groups%20of%208192.)

> Thanks, by the way for the clear information on the bug. Because of that I know precisely what the problem is and what can be done about it.
> I sadly don't have the means to look at this the coming days, but I will try to look at it as soon as I can.

Absolutely, happy to help! :)

**Comment by FPtje** [comment]
Today is the day! I've had time to look at it, and solved it in https://github.com/FPtje/Falcos-Prop-protection/commit/008e2f9ecfb14be1f46e4c5b4f02a19cef1095b2. The trick was to first find out what the limit was (it's 5825 entities, with 5826 it breaks), and then cut the net message up into pieces.

There is still some limit of entities, somewhere between 17475 and 24000 entities. When you hit that limit, the client disconnects with the error `Disconnect: Client 0 overflowed reliable channel..` but since that's way above the entity limit of 16384, I think that's fine.

I _think_ that can happen if there are more big net messages sent by other addons at the same time. That could happen when a player joins a server, but let's cross that bridge when we get to it.
