### ISSUE TITLE
Antispam breaks E2's

### ISSUE THREAD

**Issue by wrefgtzweve** [FPtje/Falcos-Prop-protection#331]
sv: Expression 2 (e2name): Internal error 'lua/fpp/server/antispam.lua:159: attempt to call a number value' at line 225, char 9

Wiremod structurally changed how e2 works so the FPP logic for it no longer seems to work.
https://github.com/FPtje/Falcos-Prop-protection/blob/master/lua/fpp/server/antispam.lua#L161

A new way to do it:
```lua
local setMaterialTbl = wire_expression2_funcs["setMaterial(e:s)"]
local ogSetMaterial = setMaterialTbl[3]
local function newSetMaterial( chip, args )
    PrintTable(args)

    ogSetMaterial( chip, args )
end

wire_expression2_funcs["setMaterial(e:s)"][3] = newSetMaterial
```

**Comment by FPtje** [comment]
Thanks for reporting! Is overriding functions still the best way to go at it? Maybe this could be an opportunity to do something better.

Whatever we do, we should probably remain compatible with the old way, to make sure FPP works with both the old and the newer version.

**Comment by wrefgtzweve** [comment]
I think it's still the best way to do it yeah, there's no hooks or anything for it https://github.com/wiremod/wire/blob/master/lua/entities/gmod_wire_expression2/core/entity.lua#L595-L603

**Comment by FPtje** [comment]
This new way you describe appears to be semantically equivalent to the way it is currently done in FPP. It appears that the error is on this line, which is within the function override:

```lua
local ent = args[2][1](self, args[2]) -- Assumption: args[2][1] is a function
```

It looks like the assumption is now false, and that `args[2][1]` is now somehow a number instead of a function.

**Comment by FPtje** [comment]
Looks like the fix is in using a different argument. I did come to realize, though, that there's apparently an `applyForce(v)` function as well, which is not overridden at all. 

That and there appear to be a bunch of other E2 functions that are not covered by this antiminge. I don't suppose I'm the first one to find out about this, is feature still in use? Because I've never seen a complaint about this.

**Comment by wrefgtzweve** [comment]
Yeah there's a billion ways to abuse e2s, if it isn't physics its something as simple as putting holos over peoples faces and blinding them. I don't think many servers if any use this feature right now.

**Comment by FPtje** [comment]
Haha yeah I remember that. Still, back in the day this pretty much stopped the physics kill thing

**Comment by wrefgtzweve** [comment]
My favourite gotta be igniting a holo and parenting it to a player
