### ISSUE TITLE
Usergroup not allowed Tools / All props blacklist randomly

### ISSUE THREAD

**Issue by DigitalSpit** [FPtje/Falcos-Prop-protection#8]
Occasionally the server will blacklist all props and the only way to remedy this issue is to restart / change the server map (Is it establishing connection to the database?)

Also all of the "users" groups tools will be blocked even though we haven't blocked all of it's tools. Any Help?

**Comment by GovernmentMan** [comment]
I know this is a dead thread but this is the only one I have found that talks about this issue. 
After the server restarts no-one except superadmins can use toolguns.
The only way to fix it temporarily is: Open Q menu, Utilities Tab, Falco's Prop Protection -> Admin settings, Group Tool Restriction. Load groups, select NoAccess. "Allow all tools by default" is checked. When I uncheck this the issue is fixed. Every time the server restarts the box gets rechecked.

**Comment by FPtje** [comment]
@GovernmentMan A regression was fixed on November 24th 2018. Can you confirm you have a version later than that?

Also, if you're running DarkRP, could you run `darkrp_check_db_sv` in console and check the output?

**Comment by GovernmentMan** [comment]
Lol honestly I was expecting there to be some large log from whatever command you were to give but I ended up with, "Your sv.db database file is good."

**Comment by GovernmentMan** [comment]
How do I find the version info?

**Comment by FPtje** [comment]
When in doubt whether you have the latest version just install latest from GitHub or the workshop. When using DarkRP just make sure DarkRP is up to date and you don't have FPP installed separately.

**Comment by CyanFlare** [comment]
Hello @FPtje ,
I'm with @GovernmentMan . The current DarkRP version we are using is the most recent version from the GitHub. We are using FPP that comes with DarkRP.

**Comment by FPtje** [comment]
What are the settings of the "user" group in FPP?
Do you use FAdmin?

**Comment by GovernmentMan** [comment]
Sorry for the late response. 
I thought Cyan was taking over the conversation from here since he's the Dev.

We do use FAdmin.
Not sure what exactly you mean by settings but I have screencaps of the in-game menu.
First one is showing the "Allow all tools by default" box checked on server reset:
https://steamuserimages-a.akamaihd.net/ugc/954108744278225062/D026D8A699FF4E2FBEE0615CA8506DDACFF5F996/

Second is the "tools currently in user" on server reset:
https://steamuserimages-a.akamaihd.net/ugc/954108744278225291/0D438DDFF3FDA816DDD5181EB058E0E8C6D932AE/

**Comment by FPtje** [comment]
I think I'll have to join to investigate. Could you mail me with connection details? (fpeijnenburg@gmail.com)

**Comment by GovernmentMan** [comment]
We would be honored to have you on, I'll get one of the server owners to send you the details. Thank you

**Comment by GovernmentMan** [comment]
That seems to have fixed the problem, thank you so much!

**Comment by FPtje** [comment]
Awesome!

**Comment by AlohaSteam** [comment]
Hi, sorry for re-opening the thread a year later. But I am having the same problem that GovernmentMan was having, I was wondering your solution to it.

**Comment by AlohaSteam** [comment]
I ran the debug and here is my output https://pastebin.com/HwfwZY37

**Comment by FPtje** [comment]
Looks like that debug script doesn't work with the latest version of FPP. What happens when you run `darkrp_check_db_sv` in the server console?

This is assuming you run DarkRP

**Comment by AlohaSteam** [comment]
"Your sv.db database file is good."

**Comment by FPtje** [comment]
Well, the good news is that FPP works nothing like how it did when this issue was created. I'm thinking the most likely cause is that some addon is preventing FPP from loading properly and loading the settings. This can happen silently or with an error on startup. Please look in your server console for errors. If you can't find any, try uninstalling addons until the problem is solved.

**Comment by AlohaSteam** [comment]
There was no error's in console but i do have the addon Prop Control System, do you know of any problems with that addon? Also if its any help you can join the server and i can give you superadmin permissions to mess around with the settings.

**Comment by AlohaSteam** [comment]
I have found a separate addon for restricting tools, thank you for your support I believe i solved my issue.
